import datetime
import uuid
from typing import Optional

from pydantic import BaseModel
from sqlalchemy import Boolean, Column, DateTime, Integer, String, Text
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class ConnectionProfile(Base):
    __tablename__ = "connection_profiles"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, nullable=False)
    db_type = Column(String, nullable=False)  # "postgresql" | "mysql" | "mssql"
    host = Column(String, nullable=False)
    port = Column(Integer, nullable=False)
    database = Column(String, nullable=False)
    username = Column(String, nullable=False)
    credential_key = Column(String, nullable=False)  # Keychain ref — NOT the password
    read_only = Column(Boolean, default=False)
    row_limit = Column(Integer, default=1000)
    query_timeout_seconds = Column(Integer, default=30)
    persona_mode = Column(String, default="analyst")  # "analyst" | "developer" | "dba"
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(
        DateTime,
        default=datetime.datetime.utcnow,
        onupdate=datetime.datetime.utcnow,
    )


class ConnectionStatus(BaseModel):
    """
    In-memory ONLY. Never persisted to SQLite.
    Use a Pydantic model, NOT a SQLAlchemy Base subclass.
    Reset to 'disconnected' on every backend restart. [TR-1]
    """

    connection_profile_id: str
    status: str  # "connected" | "error" | "connecting" | "disconnected"
    latency_ms: Optional[int] = None
    last_error: Optional[str] = None
    db_version: Optional[str] = None


class ChatSession(Base):
    __tablename__ = "chat_sessions"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    connection_profile_id = Column(String, nullable=False)
    title = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    last_active_at = Column(DateTime, default=datetime.datetime.utcnow)


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, nullable=False)
    role = Column(String, nullable=False)  # "user" | "assistant"
    content = Column(Text, nullable=False)
    sql_generated = Column(Text, nullable=True)
    # True if SQL in this message was initially generated by the AI,
    # even if the user subsequently edited it before execution.
    # Used to decide whether to show the "Approve & Learn" prompt.
    # Do NOT interpret as "the current SQL is exactly as the AI wrote it." [TR-14]
    originated_from_ai = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


class LearnedPair(Base):
    __tablename__ = "learned_pairs"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    connection_profile_id = Column(String, nullable=False)
    chroma_id = Column(String, nullable=False)  # ChromaDB document ID cross-reference
    nl_question = Column(Text, nullable=False)
    sql = Column(Text, nullable=False)
    schema_hash = Column(String, nullable=False)  # Schema hash at time of approval
    session_id = Column(String, nullable=False)
    is_flagged = Column(Boolean, default=False)  # True if schema changed since approval
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(
        DateTime,
        default=datetime.datetime.utcnow,
        onupdate=datetime.datetime.utcnow,
    )


class SchemaSnapshot(Base):
    __tablename__ = "schema_snapshots"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    connection_profile_id = Column(String, nullable=False)
    schema_hash = Column(String, nullable=False)
    schema_json = Column(Text, nullable=False)
    captured_at = Column(DateTime, default=datetime.datetime.utcnow)


class UploadedDocument(Base):
    __tablename__ = "uploaded_documents"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    connection_profile_id = Column(String, nullable=False)
    filename = Column(String, nullable=False)
    file_type = Column(String, nullable=False)  # "pdf" | "docx" | "txt" | "md"
    indexing_status = Column(
        String, default="pending"
    )  # "pending" | "indexed" | "error"
    chroma_ids = Column(Text, nullable=True)  # JSON array of chroma chunk IDs
    uploaded_at = Column(DateTime, default=datetime.datetime.utcnow)
